#Using a list of tuples
#May need to import a list from a file and load that into a dictionary, everytime the program is ran
#I need to build a function that generates a regex string
#Only if the same regex string does not exist in the list already
#If it does exist, I need to find the most recent/longest string generated by the regex
    #This can be done because the program will build the regex one token at a time

import re

def regex_gen (textImported):
    test =""

def regex_checker(textChecker):
    test = ""



